// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCustomEquipment(arg1, arg2) {
  return window['go']['main']['App']['DeleteCustomEquipment'](arg1, arg2);
}

export function DeleteCustomSpell(arg1) {
  return window['go']['main']['App']['DeleteCustomSpell'](arg1);
}

export function GetBackgrounds() {
  return window['go']['main']['App']['GetBackgrounds']();
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function GetCharacter(arg1) {
  return window['go']['main']['App']['GetCharacter'](arg1);
}

export function GetCharacterState(arg1) {
  return window['go']['main']['App']['GetCharacterState'](arg1);
}

export function GetClasses() {
  return window['go']['main']['App']['GetClasses']();
}

export function GetEquipment() {
  return window['go']['main']['App']['GetEquipment']();
}

export function GetFeats() {
  return window['go']['main']['App']['GetFeats']();
}

export function GetRaces() {
  return window['go']['main']['App']['GetRaces']();
}

export function GetSpells() {
  return window['go']['main']['App']['GetSpells']();
}

export function ListCharacters() {
  return window['go']['main']['App']['ListCharacters']();
}

export function SaveCharacter(arg1) {
  return window['go']['main']['App']['SaveCharacter'](arg1);
}

export function SaveCharacterState(arg1, arg2) {
  return window['go']['main']['App']['SaveCharacterState'](arg1, arg2);
}

export function SaveCustomEquipment(arg1, arg2) {
  return window['go']['main']['App']['SaveCustomEquipment'](arg1, arg2);
}

export function SaveCustomSpell(arg1) {
  return window['go']['main']['App']['SaveCustomSpell'](arg1);
}
