// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteCustomEquipment(arg1:string,arg2:string):Promise<void>;

export function DeleteCustomSpell(arg1:string):Promise<void>;

export function GetBackgrounds():Promise<Array<main.Background>>;

export function GetCatalog():Promise<main.Catalog>;

export function GetCharacter(arg1:string):Promise<Record<string, any>>;

export function GetCharacterState(arg1:string):Promise<Record<string, any>>;

export function GetClasses():Promise<Array<main.Class>>;

export function GetEquipment():Promise<main.Equipment>;

export function GetFeats():Promise<Array<main.Feat>>;

export function GetRaces():Promise<Array<main.Race>>;

export function GetSpells():Promise<Array<main.Spell>>;

export function ListCharacters():Promise<Array<main.CharacterSummary>>;

export function Ready():Promise<void>;

export function SaveCharacter(arg1:string):Promise<string>;

export function SaveCharacterState(arg1:string,arg2:string):Promise<void>;

export function SaveCustomEquipment(arg1:string,arg2:string):Promise<string>;

export function SaveCustomSpell(arg1:string):Promise<string>;
